In [94]:
from sympy import Matrix, S
from sympy.stats import ContinuousMarkovChain
import numpy as np
import pandas

In [95]:
P = np.loadtxt('DTMC.csv', delimiter=',', dtype=np.float32)

In [96]:
P[np.diag_indices_from(P)]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0.], dtype=float32)

In [104]:
# Initialize the CTMC generator matrix `Q` with all zeros
Q = np.divide(np.ones_like(P), P, where=P != 0)
Q[P==0] = 0
Q[np.diag_indices_from(Q)] = 0
Q[np.diag_indices_from(Q)] = -1 * Q.sum(axis=1)

In [103]:
Q.sum(axis=1)

array([ 0.0000000e+00,  3.8146973e-06,  0.0000000e+00, -3.8146973e-06,
        3.8146973e-06,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
        0.0000000e+00,  7.6293945e-06,  1.9073486e-06,  0.0000000e+00,
       -7.6293945e-06,  0.0000000e+00,  0.0000000e+00, -3.8146973e-06,
        0.0000000e+00,  0.0000000e+00,  3.8146973e-06, -3.8146973e-06,
       -3.0994415e-06,  0.0000000e+00, -7.6293945e-06, -7.6293945e-06,
        3.0517578e-05,  0.0000000e+00,  1.5258789e-05,  3.8146973e-06,
        3.8146973e-06,  5.2452087e-06,  0.0000000e+00, -3.8146973e-06,
        0.0000000e+00,  0.0000000e+00,  3.8146973e-06,  1.6689301e-06,
       -2.2649765e-06,  0.0000000e+00,  0.0000000e+00,  3.8146973e-06,
       -3.8146973e-06, -2.8610229e-06,  3.8146973e-06,  2.8610229e-06,
        0.0000000e+00,  0.0000000e+00,  0.0000000e+00, -3.0517578e-05,
       -8.3446503e-07,  3.8146973e-06,  9.5367432e-07, -1.5258789e-05,
        3.0517578e-05, -3.0517578e-05, -1.7929077e-04, -1.4305115e-04,
      

In [85]:
Q

array([[-1.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0., -1.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0., -1., ...,  0.,  0.,  0.],
       ...,
       [ 0.,  0.,  0., ..., -0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0., -0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0., -0.]], dtype=float32)

In [105]:
ctmc = ContinuousMarkovChain('C', state_space=list(range(19*3)), gen_mat=Matrix(Q))


In [107]:
ctmc.limiting_distribution()

IndexError: list index out of range